Fix LM Modify template render for tree-sitter lang (#79)
- LM Modify was not working for languages other than Python because the
  tree-sitter node cannot be pickled.
- Don't use dataclasses.asdict (which performs deep copies), instead
  perform a shallow copy.

Fixes:

```
TypeError: cannot pickle 'tree_sitter.Node' object
```